name: velocit
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^0.13.5
  fluttertoast: ^8.1.1
  another_flushbar: ^1.12.29
  flutter_svg: ^1.1.6

  google_fonts: ^3.0.1
  pin_code_text_field: ^1.8.0
  flutter_keyboard_visibility: ^5.3.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
#  carousel_pro: ^1.0.0
  carousel_slider: ^4.1.1
  flutter_barcode_scanner: ^2.0.0
  uuid: ^3.0.6
  path_provider: ^2.0.11
  insta_image_viewer: ^1.0.2


  pdf: ^3.8.4
  barcode_finder: ^0.0.5
  file_picker: ^5.2.2
  intl_phone_field: ^3.1.0
  image_picker: ^0.8.6
  permission_handler: ^10.2.0

  flutter_google_places: ^0.3.0
  dotted_border: ^2.0.0+3

  # map
  google_maps_flutter: ^2.2.1
  location: ^4.4.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  geocode: ^1.0.2
  get: ^4.6.5

  #  text to speech
  speech_to_text: ^6.0.0
  avatar_glow: ^2.0.2
  highlight_text: ^1.4.1

  flutter_rating_bar: ^4.0.1
  get_storage: ^2.0.3
  flutter_staggered_grid_view: ^0.6.2
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/appImages/
    - assets/appImages/bottomApp/
    - assets/icons/
    - assets/jsonData.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
