enum apiEndPoint {
  auth_signUp_using_post,
  get_product_categories,
  signIn_authenticate_get,

  // get_product_by_sub_categories,
  // signIn_authenticateWithUID_post,
  auth_signIn_using_post,
  user_get,
  user_post,
  get_shopByCategories,
  get_bookOurServices,
  // get_productsListing,
  get_products,
  put_carts,
  cart_create_retrive,
  cart_update,
  cart_by_ID,
  cart_by_Embedded_ID,
  single_product_scanner,
  single_product,
  send_Cart_For_Payment,
  address_list,
  add_address,
}
